export enum AuditAction {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_EXPIRED = 'ORDER_EXPIRED',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_EDITED = 'ORDER_EDITED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
}
