export enum AuditAction {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_EXPIRED = 'ORDER_EXPIRED',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_EDITED = 'ORDER_EDITED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',

  // Phase 4 Audit Actions
  INVENTORY_REFILLED = 'INVENTORY_REFILLED',
  INVENTORY_ADJUSTED = 'INVENTORY_ADJUSTED',
  INVENTORY_CONSUMED = 'INVENTORY_CONSUMED',
  INVENTORY_REVERSED = 'INVENTORY_REVERSED',
  OFFER_CREATED = 'OFFER_CREATED',
  OFFER_UPDATED = 'OFFER_UPDATED',
  OFFER_DEACTIVATED = 'OFFER_DEACTIVATED',
  OFFER_APPLIED = 'OFFER_APPLIED',
  COUPON_CREATED = 'COUPON_CREATED',
  COUPON_UPDATED = 'COUPON_UPDATED',
  COUPON_DEACTIVATED = 'COUPON_DEACTIVATED',
  COUPON_APPLIED = 'COUPON_APPLIED',

  // Phase 5 Audit Actions
  BRANCH_CREATED = 'BRANCH_CREATED',
  BRANCH_UPDATED = 'BRANCH_UPDATED',
  BRANCH_DEACTIVATED = 'BRANCH_DEACTIVATED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  DATA_DELETION_REQUESTED = 'DATA_DELETION_REQUESTED',
  DATA_DELETED = 'DATA_DELETED',
  DATA_ANONYMIZED = 'DATA_ANONYMIZED',
}
