export enum InventoryMovementType {
  ORDER_CONSUMPTION = 'ORDER_CONSUMPTION',
  RAW_MATERIAL_CONSUMPTION = 'RAW_MATERIAL_CONSUMPTION',
  REFILL = 'REFILL',
  ADJUSTMENT = 'ADJUSTMENT',
  DAMAGE = 'DAMAGE',
  WASTE = 'WASTE',
  CORRECTION = 'CORRECTION',
}

export enum InventoryItemType {
  FINISHED_PRODUCT = 'FINISHED_PRODUCT',
  RAW_MATERIAL = 'RAW_MATERIAL',
}
